### ISSUE TITLE
generate.py throws error

### ISSUE THREAD

**Issue by abuvaneswari** [dhgrs/chainer-VQ-VAE#10]
Hello,
I am successful in building a VCTK model by executing train.py as per your instructions. Thank you.

But I have the following issue while generating:
Python 3.6
Chainer 5.1.0

python generate.py --input /nas3/tfs/VCTK-Corpus/wav48/p260/p260_020.wav --output gen_p260_p361_020.wav --speaker 103 --model 2019_01_13_13_00_29/snapshot_iter_150000 -g 4

  requirement=requirement, help=help))
Traceback (most recent call last):
  File "generate.py", line 141, in <module>
    p=chainer.functions.softmax(out).array[0, :, 0, 0])
  File "/home/tfs/venv_chainer_vqvae/lib/python3.6/site-packages/cupy/random/sample.py", line 192, in choice
    return rs.choice(a, size, replace, p)
  File "/home/tfs/venv_chainer_vqvae/lib/python3.6/site-packages/cupy/random/generator.py", line 654, in choice
    raise NotImplementedError

Please let me know if I am doing anything wrong and if you have any fixes for this.

thanks

**Comment by dhgrs** [comment]
Hi,

Please check this issue.
https://github.com/dhgrs/chainer-Fast-WaveNet/issues/4

It would help you.
